name: QA pass
description: Run a manual test pass
type: test
body:
  - type: textarea
    id: scope
    attributes:
      label: What to test
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Done when
    validations:
      required: false
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - MedicueCore
        - MedicuePro
        - MedicueApp
        - MedicueOmMeg
        - MedicueApiExternal
        - MedicueApiPublic
        - MedicueService
        - Tools
    validations:
      required: false
