name: Test coverage
description: Add new automated test coverage
type: test
projects: [medicue/2]
body:
  - type: textarea
    id: scope
    attributes:
      label: What needs coverage
    validations:
      required: true
  - type: textarea
    id: cases
    attributes:
      label: Suggested test cases
    validations:
      required: false
